### ISSUE TITLE
How about replace session with interface

### ISSUE THREAD

**Issue by sevennt** [go-cas/cas#30]
Hi, @geoffgarside . How about replace session with an sessionStore interface? so we can inplement this interface with redisStore.

For now, session data was kept in memory, when we deploy multi web server instances, session data was not be shared between those instances. Meanwhile, when we restart instance, those session data has been flushed. 

It's now very convenient to use.

**Comment by bbiao** [comment]
Have the same problem, want the same feature

**Comment by bbiao** [comment]
@sevennt Hi，this is already done in the newest commit.

Happy coding with go-cas!
