### ISSUE TITLE
Bug validate can‘t use client URLSchema

### ISSUE THREAD

**Issue by RyouZhang** [go-cas/cas#35]
custom client URLSchema

But in ServiceTicketValidator，ServiceValidateUrl then path is hard-code？？？

func (validator *ServiceTicketValidator) ServiceValidateUrl(serviceUrl *url.URL, ticket string) (string, error) {
	u, err := validator.casUrl.Parse(path.Join(validator.casUrl.Path, "serviceValidate"))

**Comment by geoffgarside** [comment]
Hi, the CAS URIs are a codified part of the specification

https://apereo.github.io/cas/5.1.x/protocol/CAS-Protocol-Specification.html#2-cas-uris
