### ISSUE TITLE
[bug] wrong key is passed to session deletion when logout

### ISSUE THREAD

**Issue by tslling** [go-cas/cas#36]
AFAIK, the mapping between cookie, session and ticket are as follow:
cookie key --> cookie value(also session key)
session key --> session value(also service ticket)
service ticket --> authentication info.
https://github.com/go-cas/cas/blob/87e080a1b4e591c5fd37174b61bad67431ca3524/client.go#L356-L365

```c.sessions.Get(cookie.Value)``` gets the session value(also the service ticket), while ```c.deleteSession()``` should receive the session key as the parameter. We passed session **value** as session **key**, so the ```deleteSession``` does not work here.

**Comment by bbiao** [comment]
This issue has been fixed by @tslling 
I will release a new version in following days.

**Comment by bbiao** [comment]
This bugfix was released in v2.2.1.
