### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Antimidget** [go-cas/cas#4]
I've been trying to get your library working, it auths correctly and the ticket it gets back is correct, but i keep running into the fact that `cas.IsAuthenticated(r)` always returns false.

I thought i was doing something wrong so i copied and pasted your example word for word and again it comes back false and sits in a loop redirecting back to the cas server.

Is it possible to have an updated example, or even confirmation that it is correct as is.

Thank you
~Anti

**Comment by Antimidget** [comment]
No longer an issue, Network configuration issue

**Comment by zsr228** [comment]
> No longer an issue, Network configuration issue

I want to know, how did you solve it

**Comment by Antimidget** [comment]
I don't remember exactly, it was to do with DNS lookup not returning the CAS server, i had to use the ip address.

Sorry to say i no longer have access to the code i was writing as it's ownership was the company i was working for at the time

**Comment by zsr228** [comment]
> I don't remember exactly, it was to do with DNS lookup not returning the CAS server, i had to use the ip address.
> 
> Sorry to say i no longer have access to the code i was writing as it's ownership was the company i was working for at the time

I have used ip address, but it still occur TOO_MANY_REDIRECTS

**Comment by geoffgarside** [comment]
This would likely occur if the authenticating application (calling `cas.IsAuthenticated`) cannot communicate (request /serviceValidate) with the CAS server. It may interpret this as not-authenticated so redirects the client to the CAS server to login. The CAS server thinks the user is logged in as the TGT cookie is present, so redirects the client back to the Application.

**Comment by zsr228** [comment]
> This would likely occur if the authenticating application (calling `cas.IsAuthenticated`) cannot communicate (request /serviceValidate) with the CAS server. It may interpret this as not-authenticated so redirects the client to the CAS server to login. The CAS server thinks the user is logged in as the TGT cookie is present, so redirects the client back to the Application.

yes, you are right。when I use cas.IsAuthenticated funcation it return false, so I use client.RedirectToLogin function, then occur TOO_MANY_REDIRECTS。 but why cas.IsAuthenticated always return false 。

**Comment by zsr228** [comment]
> This would likely occur if the authenticating application (calling `cas.IsAuthenticated`) cannot communicate (request /serviceValidate) with the CAS server. It may interpret this as not-authenticated so redirects the client to the CAS server to login. The CAS server thinks the user is logged in as the TGT cookie is present, so redirects the client back to the Application.

I found, before new this client, we require register this client to cas。
