### ISSUE TITLE
How to set this up on Google App Engine? (Keep getting redirect error)

### ISSUE THREAD

**Issue by chriswalz** [go-cas/cas#5]
Hello, thank you for this library. I have it set up on Google App Engine however I needed to modify the example a bit since it needs to run in **init()**. It's worth pointing that I got it working when I wasn't using app engine. 

Any idea why I would get a redirect infinite loop? What appears to be happening is my server redirects to cas server and then the cas server redirects back to my server and then my server redirects back to the cas server forever. 

```
func init() {
	flag.StringVar(&casURL, "url", "", "CAS server URL")
	flag.Parse()

	casURL = "URLREMOVED"
	if casURL == "" {
		flag.Usage()
		return
	}
	//glog.Info("Starting up")

	m := http.NewServeMux()

	m.Handle("/", MyHandler)

	url, _ := url.Parse(casURL)
	client := cas.NewClient(&cas.Options{
		URL: url,
	})

	http.Handle("/", client.Handle(m)) // <--- is the error related to this line?
}```

**Comment by geoffgarside** [comment]
I think the line you've highlighted is where the error is. I'm not very familiar with Google App Engine, where do you do the `http.ListenAndServe(":80", handler)` part? The `client.Handle(m)` should be passed to the `ListenAndServe` function.

Something like this

``` go
func init() {
  // ... snipped ...

  url, _ := url.Parse(casURL)
  client := cas.NewClient(&cas.Options{
    URL: url,
  })

  http.ListenAndServe(":80", client.Handle(m))
}
```

The cas package works as a middleware rather than a specific route handler, so it needs to see every request (well every one it would need to be protecting) as a user could potentially land on your site at any path.

**Comment by chriswalz** [comment]
What's a bit strange about Google App Engine is that it appears that it calls ListenAndServe on its own :(

**Comment by geoffgarside** [comment]
Are you able to create the instance of the `http.Server` which Google App Engine will then start? You can create it like

```go
server := &http.Server{Handler: client.Handle(m)}
```

**Comment by geoffgarside** [comment]
The only thing I can find about it is https://cloud.google.com/appengine/docs/go/users but I'm not overly sure what you'd need to do to handle the authentication process yourself

**Comment by chriswalz** [comment]
I decide to use AWS elastic beanstalk since it allows a main function. It's working now.
