### ISSUE TITLE
Can not use gopkg.in/cas.v1 in beego? How?

### ISSUE THREAD

**Issue by adanteng** [go-cas/cas#6]
Seen your code. 

Use clientHandler(handler.go) to wrap the real user's handler. 

But the problem is beego already wrap http.Handler, user no need to create own handler, just Controller + Router will work fine.

So i create a beego_helpers.go in the project to do some tricky thing. I am an new goer,  I think you can come out a better solution.

beego is a web framework. beego.me

beego_helper.go:

```
package cas

import (
	"net/http"

	"github.com/golang/glog"
)

type BeegoCASData struct {
	userName string
}

func (bcd *BeegoCASData) GetUserName() string {
	return bcd.userName
}

func ServeBeego(w http.ResponseWriter, r *http.Request, c *Client) *BeegoCASData {
	if glog.V(2) {
		glog.Infof("cas: handling %v request for %v", r.Method, r.URL)
	}

	setClient(r, c)
	defer clear(r)

	c.getSession(w, r)

	if !IsAuthenticated(r) {
		RedirectToLogin(w, r)
		return nil
	}

	if r.URL.Path == "/logout" {
		RedirectToLogout(w, r)
		return nil
	}

	return &BeegoCASData{
		userName: Username(r),
	}
}
```

**Comment by geoffgarside** [comment]
I'm not familiar with beego, but you might need to look at how you use other `ServeHTTP` based middleware with beego. With a casual glance it looks like you'd either need to implement the Session interfaces, or somehow wrap the app.Handlers. I'm not sure of the correct place within beego to add authentication handling, but the `GlobalSession` might be the right place.

**Comment by adanteng** [comment]
Thanks for reply.

With beego, I can create filter to pre-process each request before router url and logic process in `Controller`. Filter can be the correct place to add authentication handling. 

`ServeHTTP` wrap in beego's core code, and beego remove `http.Handler` management from app logic. Developer just declare some get or post method in `Controller` to handle bussiness logic.

I think remove `ServeHTTP` logic from your cas lib or provide more helper method to assist web framework developer, and only focus on the interaction with cas server base on the http://jasig.github.io/cas/4.0.x/protocol/CAS-Protocol.html may be a good idea. 

Make `ServeHTTP` like bonus for some developer which use origin go method `ServeHTTP`.

I am a new goer, if i am wrong, do not pissed off.

**Comment by geoffgarside** [comment]
We could probably move the `ServeHTTP` logic into another function, or set of functions, which `ServeHTTP` then wraps. This would allow HTTP frameworks which hide the standard `http.Handler` interface to still make use of the package.

The problem is the CAS handler needs to be a middleware. It has to see every request that comes in which its supposed to be protecting, regardless of HTTP method. This is particularly important for the Single Log Out behaviour as the URL to which the Single Log Out notification is `POST`ed to will be whatever the client was originally redirected to the CAS server from, so its not possible to know in advance where this request will be sent.

**Comment by adanteng** [comment]
Look forward to the change which will support web framework.

Looks like CAS handler wrap some important work for developer use standard `http.Handler`. Before I create a new helper to handle the compatible with beego.

**Comment by dijingran** [comment]
@adanteng  the beego_helper  works fine!
